title: Maria Butkovic
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi my name is Maria.
  <br><br> # this is spaces between lines
  <br><br>
  This is my second description.
  <br><br>
  <a href="url">"www.linkedin.com/in/maria-b-b2997912">View My LinkedIn Profile</a> 
  <br><br>
  # <a href=“url”>name of the url</a> this is how you add more links
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
